---
title: "R Notebook - DE Annotation - Fibroblasts"
output: html_notebook
---

```{r}
library(Seurat)
library(dplyr)
library(ggplot2)
library(patchwork)
library(tidyr)
```

```{r}
singlets <- readRDS("/Volumes/srivalli/dzhi/ACM_SN_R_2025/data_ctrl_noninf/singlets_de_annotated.rds")
singlets
```

```{r}
singlets_fb <- subset(
  singlets,
  subset = grepl("Fibroblast", DE_Annotation_broad)
)
singlets_fb
```
```{r}
# PCA
singlets_fb <- FindVariableFeatures(singlets_fb, selection.method = "vst", nfeatures = 3000)
singlets_fb <- ScaleData(singlets_fb)
singlets_fb <- RunPCA(singlets_fb, npcs = 30)

# Determine dimensionality
ElbowPlot(singlets_fb, ndims = 30)
```

```{r}
# Neighbors
singlets_fb <- FindNeighbors(singlets_fb, dims = 1:25)
singlets_fb <- FindClusters(singlets_fb, resolution = 0.5)  
singlets_fb <- RunUMAP(singlets_fb, dims = 1:25)
```

```{r}
p_fb_umap <- DimPlot(singlets_fb, reduction = "umap", label = TRUE) +
  ggtitle("fb Subclusters")
p_fb_umap
ggsave("/Volumes/srivalli/dzhi/ACM_SN_R_2025/plots_ctrl_noninf/umap_fb_subclusters.png", p_fb_umap, width = 8, height = 6)
```

```{r}
Idents(singlets_fb) <- "seurat_clusters"

# Find all markers between clusters
fb_markers <- FindAllMarkers(
  singlets_fb,
  assay = "RNA",
  only.pos = TRUE,
  min.pct = 0.25,
  logfc.threshold = 0.25
)
```

```{r}
write.csv(fb_markers, "/Volumes/srivalli/dzhi/ACM_SN_R_2025/data_ctrl_noninf/fb_subcluster_markers.csv")

# DotPlot for top 5 markers per cluster
top5 <- fb_markers %>%
  group_by(cluster) %>%
  top_n(n = 5, wt = avg_log2FC)

top10 <- fb_markers %>%
  group_by(cluster) %>%
  top_n(n = 10, wt = avg_log2FC) %>%
  arrange(cluster, desc(avg_log2FC))

write.csv(top10, "/Volumes/srivalli/dzhi/ACM_SN_R_2025/data_ctrl_noninf/Top10_fb_Subcluster_Markers.csv", row.names = FALSE)

p0 <- DotPlot(singlets_fb, features = unique(top5$gene)) + RotatedAxis()
p0
ggsave("/Volumes/srivalli/dzhi/ACM_SN_R_2025/plots_ctrl_noninf/fb_subcluster_markers.png",p0,height = 10, width = 20)
```

```{r}
fb_cluster_annotations <- c(
  "0" = "Mature/Quiescent FB",
  "1" = "Activated/Remodeling FB",
  "2" = "Pro-regenerative/Signaling FB",
  "3" = "Vascular-Associated/Perivascular FB",
  "4" = "Developmental/Transitional FB",
  "5" = "Activated/ECM-modifying FB",
  "6" = "CM-like/Hybrid FB (Possible Doublets)",
  "7" = "Endothelial-like/Angiogenic FB",
  "8" = "Neural/Signaling FB",
  "9" = "Pro-regenerative/Perivascular FB",
  "10" = "Interferon/Immune-Responsive FB",
  "11" = "Lymphatic/Reln+ Specialized FB"
)
```

```{r}
Idents(singlets_fb) <- singlets_fb$seurat_clusters

# Get the cluster per cell
cell_clusters <- as.character(Idents(singlets_fb))
names(cell_clusters) <- colnames(singlets_fb)

# Map cluster IDs to fb annotations
annotated_labels <- fb_cluster_annotations[cell_clusters]
names(annotated_labels) <- names(cell_clusters)

# Add as metadata
singlets_fb$fb_Cluster_Annotation <- annotated_labels
```

```{r}
Idents(singlets_fb) <- singlets_fb$fb_Cluster_Annotation

p_fb_umap2 <- DimPlot(singlets_fb, reduction = "umap",  repel = TRUE) +
  ggtitle("UMAP of Fibroblast Subclusters") +
  theme_minimal()
p_fb_umap2
ggsave("/Volumes/srivalli/dzhi/ACM_SN_R_2025/plots_ctrl_noninf/umap_fb_anno.png",
       p_fb_umap, width = 8, height = 6)
```

```{r}
df_fb <- singlets_fb@meta.data %>%
  filter(!is.na(fb_Cluster_Annotation)) %>%
  group_by(fb_Cluster_Annotation, Condition) %>%
  summarise(cell_count = n()) %>%
  ungroup()

# Plot barplot
p_bar_fb <- ggplot(df_fb, aes(x = fb_Cluster_Annotation, y = cell_count, fill = Condition)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(aes(label = cell_count), 
            position = position_dodge(width = 0.9), 
            vjust = -0.2, size = 3) +
  theme_minimal() +
  labs(x = "fb Subcluster", y = "Cell Count", fill = "Condition") +
  ggtitle("Fibroblast Subclusters per Condition") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

p_bar_fb

ggsave("/Volumes/srivalli/dzhi/ACM_SN_R_2025/plots_ctrl_noninf/fb_subcluster_barplot.png",
       p_bar_fb, width = 10, height = 6)
```

```{r}
singlets$fb_Cluster_Annotation <- NA
fb_cells <- colnames(singlets_fb)
singlets$fb_Cluster_Annotation[fb_cells] <- singlets_fb$fb_Cluster_Annotation
singlets$fb_Cluster_Annotation <- factor(singlets$fb_Cluster_Annotation)

# Plot
p_fb_on_full <- DimPlot(
  singlets,
  group.by = "fb_Cluster_Annotation",
  reduction = "umap",
  repel = TRUE,
  pt.size = 0.4
) + 
  ggtitle("fb Subclusters Overlayed on All Cells") +
  theme_minimal()
p_fb_on_full
ggsave("/Volumes/srivalli/dzhi/ACM_SN_R_2025/plots_ctrl_noninf/umap_fb_clusters_on_all_cells.png",
       p_fb_on_full, width = 10, height = 7)

```

```{r}
# Plot split by condition
p_fb_split <- DimPlot(
  singlets,
  group.by = "fb_Cluster_Annotation",
  reduction = "umap",
  repel = TRUE,
  pt.size = 0.4,
  na.value = "grey80",         # non-fb cells shown as grey
  split.by = "Condition"       # splits by condition
) +
  ggtitle("fb Subclusters Overlayed and Split by Condition") +
  theme_minimal()
p_fb_split
ggsave("/Volumes/srivalli/dzhi/ACM_SN_R_2025/plots_ctrl_noninf/umap_fb_clusters_split_by_condition.png",
       p_fb_split, width = 14, height = 6)
```

```{r}
saveRDS(singlets,"/Volumes/srivalli/dzhi/ACM_SN_R_2025/data_ctrl_noninf/singlets_fb_anno.rds")
```