---
title: "R Notebook - DE Annotation - Others"
output: html_notebook
---

```{r}
library(Seurat)
library(dplyr)
library(ggplot2)
library(patchwork)
library(tidyr)
```

```{r}
singlets <- readRDS("/Volumes/srivalli/dzhi/ACM_SN_R_2025/data_ctrl_noninf/singlets_de_annotated.rds")
singlets
```

```{r}
singlets_others <- subset(singlets, subset = DE_Annotation_broad %in% c(
  "Neuronal/Glial-like Cells",
  "Proliferating/Dividing Cells",
  "Smooth Muscle Cells (SMC)",
  "Smooth Muscle Cells (SMC)/Pericytes"
))
singlets_others
```

```{r}
unique(singlets_others@meta.data$DE_Annotation_broad)
```


```{r}
# PCA
singlets_others <- FindVariableFeatures(singlets_others, selection.method = "vst", nfeatures = 3000)
singlets_others <- ScaleData(singlets_others)
singlets_others <- RunPCA(singlets_others, npcs = 30)

# Determine dimensionality
ElbowPlot(singlets_others, ndims = 30)
```

```{r}
# Neighbors
singlets_others <- FindNeighbors(singlets_others, dims = 1:25)
singlets_others <- FindClusters(singlets_others, resolution = 0.5)  
singlets_others <- RunUMAP(singlets_others, dims = 1:25)
```

```{r}
p_others_umap <- DimPlot(singlets_others, reduction = "umap", label = TRUE) +
  ggtitle("Others Subclusters")
p_others_umap
ggsave("/Volumes/srivalli/dzhi/ACM_SN_R_2025/plots_ctrl_noninf/umap_others_subclusters.png", p_others_umap, width = 8, height = 6)
```

```{r}
Idents(singlets_others) <- "seurat_clusters"

# Find all markers between clusters
others_markers <- FindAllMarkers(
  singlets_others,
  assay = "RNA",
  only.pos = TRUE,
  min.pct = 0.25,
  logfc.threshold = 0.25
)
```

```{r}
write.csv(others_markers, "/Volumes/srivalli/dzhi/ACM_SN_R_2025/data_ctrl_noninf/others_subcluster_markers.csv")

# DotPlot for top 5 markers per cluster
top5 <- others_markers %>%
  group_by(cluster) %>%
  top_n(n = 5, wt = avg_log2FC)

top10 <- others_markers %>%
  group_by(cluster) %>%
  top_n(n = 10, wt = avg_log2FC) %>%
  arrange(cluster, desc(avg_log2FC))

write.csv(top10, "/Volumes/srivalli/dzhi/ACM_SN_R_2025/data_ctrl_noninf/Top10_others_Subcluster_Markers.csv", row.names = FALSE)

p0 <- DotPlot(singlets_others, features = unique(top5$gene)) + RotatedAxis()
p0
ggsave("/Volumes/srivalli/dzhi/ACM_SN_R_2025/plots_ctrl_noninf/others_subcluster_markers.png",p0,height = 10, width = 20)
```

```{r}
others_cluster_annotations <- c(
  "0" = "Pericyte/SMC/Neuronal Hybrid",
  "1" = "Stressed/Pro-fibrotic Cardiomyocytes",
  "2" = "Smooth Muscle Cells (SMC)",
  "3" = "Endothelial Cells",
  "4" = "Activated Macrophages/Monocytes",
  "5" = "Fibroblasts",
  "6" = "Proliferating Cells",
  "7" = "Neuronal-like Cells",
  "8" = "SMC/Pericyte/Endothelial Hybrid",
  "9" = "Pro-regenerative/Signaling Fibroblasts/Neural-like",
  "10" = "Epicardial/Mesothelial-like Cells",
  "11" = "Lymphatic Endothelial/Specialized Vascular Cells"
)
```

```{r}
Idents(singlets_others) <- singlets_others$seurat_clusters

# Get the cluster per cell
cell_clusters <- as.character(Idents(singlets_others))
names(cell_clusters) <- colnames(singlets_others)

# Map cluster IDs to others annotations
annotated_labels <- others_cluster_annotations[cell_clusters]
names(annotated_labels) <- names(cell_clusters)

# Add as metadata
singlets_others$others_Cluster_Annotation <- annotated_labels
```

```{r}
Idents(singlets_others) <- singlets_others$others_Cluster_Annotation

p_others_umap2 <- DimPlot(singlets_others, reduction = "umap",  repel = TRUE) +
  ggtitle("UMAP of othersdothelial Subclusters") +
  theme_minimal()
p_others_umap2
ggsave("/Volumes/srivalli/dzhi/ACM_SN_R_2025/plots_ctrl_noninf/umap_others_anno.png",
       p_others_umap, width = 8, height = 6)
```

```{r}
df_others <- singlets_others@meta.data %>%
  filter(!is.na(others_Cluster_Annotation)) %>%
  group_by(others_Cluster_Annotation, Condition) %>%
  summarise(cell_count = n()) %>%
  ungroup()

# Plot barplot
p_bar_others <- ggplot(df_others, aes(x = others_Cluster_Annotation, y = cell_count, fill = Condition)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(aes(label = cell_count), 
            position = position_dodge(width = 0.9), 
            vjust = -0.2, size = 3) +
  theme_minimal() +
  labs(x = "others Subcluster", y = "Cell Count", fill = "Condition") +
  ggtitle("Others Subclusters per Condition") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

p_bar_others

ggsave("/Volumes/srivalli/dzhi/ACM_SN_R_2025/plots_ctrl_noninf/others_subcluster_barplot.png",
       p_bar_others, width = 10, height = 6)
```

```{r}
singlets$others_Cluster_Annotation <- NA
others_cells <- colnames(singlets_others)
singlets$others_Cluster_Annotation[others_cells] <- singlets_others$others_Cluster_Annotation
singlets$others_Cluster_Annotation <- factor(singlets$others_Cluster_Annotation)

# Plot
p_others_on_full <- DimPlot(
  singlets,
  group.by = "others_Cluster_Annotation",
  reduction = "umap",
  repel = TRUE,
  pt.size = 0.4
) + 
  ggtitle("others Subclusters Overlayed on All Cells") +
  theme_minimal()
p_others_on_full
ggsave("/Volumes/srivalli/dzhi/ACM_SN_R_2025/plots_ctrl_noninf/umap_others_clusters_on_all_cells.png",
       p_others_on_full, width = 10, height = 7)

```

```{r}
# Plot split by condition
p_others_split <- DimPlot(
  singlets,
  group.by = "others_Cluster_Annotation",
  reduction = "umap",
  repel = TRUE,
  pt.size = 0.4,
  na.value = "grey80",         # non-others cells shown as grey
  split.by = "Condition"       # splits by condition
) +
  ggtitle("others Subclusters Overlayed and Split by Condition") +
  theme_minimal()
p_others_split
ggsave("/Volumes/srivalli/dzhi/ACM_SN_R_2025/plots_ctrl_noninf/umap_others_clusters_split_by_condition.png",
       p_others_split, width = 14, height = 6)
```

```{r}
saveRDS(singlets,"/Volumes/srivalli/dzhi/ACM_SN_R_2025/data_ctrl_noninf/singlets_others_anno.rds")
```