---
title: "R Notebook - DE Annotation - Immune Cells"
output: html_notebook
---

```{r}
library(Seurat)
library(dplyr)
library(ggplot2)
library(patchwork)
library(tidyr)
```

```{r}
singlets <- readRDS("/Volumes/srivalli/dzhi/ACM_SN_R_2025/data_ctrl_noninf/singlets_de_annotated.rds")
singlets
```

```{r}
singlets_imm <- subset(
  singlets,
  subset = DE_Annotation_broad %in% c("B Lymphocytes", "Macrophages/Monocytes", "T Lymphocytes")
)
singlets_imm
```

```{r}
unique(singlets_imm@meta.data$DE_Annotation_broad)
```


```{r}
# PCA
singlets_imm <- FindVariableFeatures(singlets_imm, selection.method = "vst", nfeatures = 3000)
singlets_imm <- ScaleData(singlets_imm)
singlets_imm <- RunPCA(singlets_imm, npcs = 30)

# Determine dimensionality
ElbowPlot(singlets_imm, ndims = 30)
```

```{r}
# Neighbors
singlets_imm <- FindNeighbors(singlets_imm, dims = 1:25)
singlets_imm <- FindClusters(singlets_imm, resolution = 0.5)  
singlets_imm <- RunUMAP(singlets_imm, dims = 1:25)
```

```{r}
p_imm_umap <- DimPlot(singlets_imm, reduction = "umap", label = TRUE) +
  ggtitle("Immune Subclusters")
p_imm_umap
ggsave("/Volumes/srivalli/dzhi/ACM_SN_R_2025/plots_ctrl_noninf/umap_imm_subclusters.png", p_imm_umap, width = 8, height = 6)
```

```{r}
Idents(singlets_imm) <- "seurat_clusters"

# Find all markers betweimm clusters
imm_markers <- FindAllMarkers(
  singlets_imm,
  assay = "RNA",
  only.pos = TRUE,
  min.pct = 0.25,
  logfc.threshold = 0.25
)
```

```{r}
write.csv(imm_markers, "/Volumes/srivalli/dzhi/ACM_SN_R_2025/data_ctrl_noninf/imm_subcluster_markers.csv")

# DotPlot for top 5 markers per cluster
top5 <- imm_markers %>%
  group_by(cluster) %>%
  top_n(n = 5, wt = avg_log2FC)

top10 <- imm_markers %>%
  group_by(cluster) %>%
  top_n(n = 10, wt = avg_log2FC) %>%
  arrange(cluster, desc(avg_log2FC))

write.csv(top10, "/Volumes/srivalli/dzhi/ACM_SN_R_2025/data_ctrl_noninf/Top10_imm_Subcluster_Markers.csv", row.names = FALSE)

p0 <- DotPlot(singlets_imm, features = unique(top5$gene)) + RotatedAxis()
p0
ggsave("/Volumes/srivalli/dzhi/ACM_SN_R_2025/plots_ctrl_noninf/imm_subcluster_markers.png",p0,height = 10, width = 20)
```

```{r}
imm_cluster_annotations <- c(
  "0" = "Tissue Macrophages (M2-like)",
  "1" = "Activated Macrophages/Monocytes",
  "2" = "Endothelial-like/Immune Interacting",
  "3" = "Antigen-Presenting Cells (APCs)",
  "4" = "CM-like/Hybrid Immune Cells (Possible Doublets)",
  "5" = "Fibroblast-like/Immune Interacting",
  "6" = "B Cells",
  "7" = "T Cells (CD4+/Th17-like)",
  "8" = "NK Cells/Granulocytes",
  "9" = "Pro-regenerative/Immune Interacting",
  "10" = "Cytotoxic T Cells (CD8+)",
  "11" = "Mesenchymal-like/Immune Interacting",
  "12" = "T Cells (CD4+/Effector)",
  "13" = "B Cells",
  "14" = "Dendritic Cells",
  "15" = "Neutrophils/Inflammatory Granulocytes"
)
```

```{r}
Idents(singlets_imm) <- singlets_imm$seurat_clusters

# Get the cluster per cell
cell_clusters <- as.character(Idents(singlets_imm))
names(cell_clusters) <- colnames(singlets_imm)

# Map cluster IDs to imm annotations
annotated_labels <- imm_cluster_annotations[cell_clusters]
names(annotated_labels) <- names(cell_clusters)

# Add as metadata
singlets_imm$imm_Cluster_Annotation <- annotated_labels
```

```{r}
Idents(singlets_imm) <- singlets_imm$imm_Cluster_Annotation

p_imm_umap2 <- DimPlot(singlets_imm, reduction = "umap",  repel = TRUE) +
  ggtitle("UMAP of immdothelial Subclusters") +
  theme_minimal()
p_imm_umap2
ggsave("/Volumes/srivalli/dzhi/ACM_SN_R_2025/plots_ctrl_noninf/umap_imm_anno.png",
       p_imm_umap, width = 8, height = 6)
```

```{r}
df_imm <- singlets_imm@meta.data %>%
  filter(!is.na(imm_Cluster_Annotation)) %>%
  group_by(imm_Cluster_Annotation, Condition) %>%
  summarise(cell_count = n()) %>%
  ungroup()

# Plot barplot
p_bar_imm <- ggplot(df_imm, aes(x = imm_Cluster_Annotation, y = cell_count, fill = Condition)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(aes(label = cell_count), 
            position = position_dodge(width = 0.9), 
            vjust = -0.2, size = 3) +
  theme_minimal() +
  labs(x = "imm Subcluster", y = "Cell Count", fill = "Condition") +
  ggtitle("Immune Subclusters per Condition") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

p_bar_imm

ggsave("/Volumes/srivalli/dzhi/ACM_SN_R_2025/plots_ctrl_noninf/imm_subcluster_barplot.png",
       p_bar_imm, width = 10, height = 6)
```

```{r}
singlets$imm_Cluster_Annotation <- NA
imm_cells <- colnames(singlets_imm)
singlets$imm_Cluster_Annotation[imm_cells] <- singlets_imm$imm_Cluster_Annotation
singlets$imm_Cluster_Annotation <- factor(singlets$imm_Cluster_Annotation)

# Plot
p_imm_on_full <- DimPlot(
  singlets,
  group.by = "imm_Cluster_Annotation",
  reduction = "umap",
  repel = TRUE,
  pt.size = 0.4
) + 
  ggtitle("imm Subclusters Overlayed on All Cells") +
  theme_minimal()
p_imm_on_full
ggsave("/Volumes/srivalli/dzhi/ACM_SN_R_2025/plots_ctrl_noninf/umap_imm_clusters_on_all_cells.png",
       p_imm_on_full, width = 10, height = 7)

```

```{r}
# Plot split by condition
p_imm_split <- DimPlot(
  singlets,
  group.by = "imm_Cluster_Annotation",
  reduction = "umap",
  repel = TRUE,
  pt.size = 0.4,
  na.value = "grey80",         # non-imm cells shown as grey
  split.by = "Condition"       # splits by condition
) +
  ggtitle("imm Subclusters Overlayed and Split by Condition") +
  theme_minimal()
p_imm_split
ggsave("/Volumes/srivalli/dzhi/ACM_SN_R_2025/plots_ctrl_noninf/umap_imm_clusters_split_by_condition.png",
       p_imm_split, width = 14, height = 6)
```

```{r}
saveRDS(singlets,"/Volumes/srivalli/dzhi/ACM_SN_R_2025/data_ctrl_noninf/singlets_imm_anno.rds")
```